# Generated by Django 5.0.4 on 2024-04-15 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='updatedat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
